spring.application.name=bfb
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs


#mongo config
spring.data.mongodb.database=bfd_application
spring.data.mongodb.host=bfb_database
spring.data.mongodb.port=27017